/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        outline: '#747a60',
        primary: '#506600',
        'inverse-surface': '#2f3131',
        'tertiary-fixed-dim': '#bfc2ff',
        'primary-container': '#ccff00',
        'secondary-fixed-dim': '#ffb1c3',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#ffd9e0',
        'tertiary-fixed': '#e0e0ff',
        'on-surface-variant': '#444933',
        'on-tertiary-fixed-variant': '#0d00ee',
        'on-primary-fixed-variant': '#3c4d00',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-variant': '#e2e2e2',
        'primary-fixed-dim': '#abd600',
        'on-secondary-fixed-variant': '#8f0041',
        'inverse-on-surface': '#f1f1f1',
        error: '#ba1a1a',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'secondary-container': '#e4006c',
        'on-primary': '#ffffff',
        surface: '#f9f9f9',
        background: '#f9f9f9',
        secondary: '#b60055',
        'on-secondary-container': '#fffbff',
        'inverse-primary': '#abd600',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#3f0019',
        'on-surface': '#1a1c1c',
        'primary-fixed': '#c3f400',
        'surface-container-low': '#f3f3f3',
        tertiary: '#373cff',
        'error-container': '#ffdad6',
        'outline-variant': '#c4c9ac',
        'surface-tint': '#506600',
        'tertiary-container': '#edebff',
        'surface-container-high': '#e8e8e8',
        'on-tertiary-container': '#4b51ff',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#02006d',
        'on-primary-fixed': '#161e00',
        'surface-container': '#eeeeee',
        'on-background': '#1a1c1c',
        'on-primary-container': '#5b7300',
        lime: {
          400: '#a3e635',
          500: '#84cc16',
        },
        gray: {
          900: '#0f0f0f',
          800: '#1a1a1a',
          700: '#2d2d2d',
        },
      },
      spacing: {
        margin: '32px',
        unit: '8px',
        gutter: '24px',
      },
      borderWidth: {
        'border-width-standard': '4px',
        'border-width-thick': '6px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        space: ['"Space Grotesk"', 'sans-serif'],
        'label-bold': ['"Space Grotesk"', 'sans-serif'],
        'label-mono': ['"Space Grotesk"', 'sans-serif'],
        'headline-xl': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['"Space Grotesk"', 'sans-serif'],
        'body-md': ['"Space Grotesk"', 'sans-serif'],
      },
      fontSize: {
        '2xl': '2.5rem',
        '3xl': '3rem',
        '4xl': '4rem',
        'label-bold': ['14px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-mono': ['12px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
